// <auto-generated />
using System;
using Drive.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drive.Data.Migrations
{
    [DbContext(typeof(DumpDriveDbContext))]
    [Migration("20241228144927_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drive.Data.Entities.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CommentId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            Content = "Komentar 1",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2345),
                            ItemId = 15,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 2,
                            Content = "Komentar 2",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2879),
                            ItemId = 16,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 3,
                            Content = "Komentar 3",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2881),
                            ItemId = 17,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 4,
                            Content = "Komentar 4",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2882),
                            ItemId = 18,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 5,
                            Content = "Komentar 5",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2883),
                            ItemId = 19,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 6,
                            Content = "Komentar 6",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2885),
                            ItemId = 20,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 7,
                            Content = "Komentar 7",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2886),
                            ItemId = 21,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 8,
                            Content = "Komentar 8",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2887),
                            ItemId = 22,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 9,
                            Content = "Komentar 9",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2887),
                            ItemId = 23,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 10,
                            Content = "Komentar 10",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2889),
                            ItemId = 24,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 11,
                            Content = "Komentar 11",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2890),
                            ItemId = 25,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 12,
                            Content = "Komentar 12",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2890),
                            ItemId = 26,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 13,
                            Content = "Komentar 13",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2891),
                            ItemId = 27,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 14,
                            Content = "Komentar 14",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2892),
                            ItemId = 28,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 15,
                            Content = "Komentar 15",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2893),
                            ItemId = 29,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 16,
                            Content = "Komentar 16",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2893),
                            ItemId = 15,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 17,
                            Content = "Komentar 17",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2894),
                            ItemId = 16,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 18,
                            Content = "Komentar 18",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2895),
                            ItemId = 17,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 19,
                            Content = "Komentar 19",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2896),
                            ItemId = 18,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 20,
                            Content = "Komentar 20",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2897),
                            ItemId = 19,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 21,
                            Content = "Komentar 21",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2898),
                            ItemId = 20,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 22,
                            Content = "Komentar 22",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2898),
                            ItemId = 21,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 23,
                            Content = "Komentar 23",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2899),
                            ItemId = 22,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 24,
                            Content = "Komentar 24",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2900),
                            ItemId = 23,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 25,
                            Content = "Komentar 25",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2901),
                            ItemId = 24,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 26,
                            Content = "Komentar 26",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2901),
                            ItemId = 25,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 27,
                            Content = "Komentar 27",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2902),
                            ItemId = 26,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 28,
                            Content = "Komentar 28",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2903),
                            ItemId = 27,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 29,
                            Content = "Komentar 29",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2904),
                            ItemId = 28,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 30,
                            Content = "Komentar 30",
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(2904),
                            ItemId = 29,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Disk", b =>
                {
                    b.Property<int>("DiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiskId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("DiskId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Disks");

                    b.HasData(
                        new
                        {
                            DiskId = 1,
                            Name = "Lukin-disk",
                            UserId = 1
                        },
                        new
                        {
                            DiskId = 2,
                            Name = "Antin-disk",
                            UserId = 2
                        },
                        new
                        {
                            DiskId = 3,
                            Name = "Matin-disk",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiskId")
                        .HasColumnType("integer");

                    b.Property<string>("Item_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("LastChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentFolderItemId")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.HasIndex("DiskId");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("ParentFolderItemId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Item_type").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.SharedItem", b =>
                {
                    b.Property<int>("SharedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SharedItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SharedItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedItems");

                    b.HasData(
                        new
                        {
                            SharedItemId = 1,
                            ItemId = 15,
                            ItemName = "domaci.docx",
                            UserId = 1
                        },
                        new
                        {
                            SharedItemId = 2,
                            ItemId = 16,
                            ItemName = "predavanje.txt",
                            UserId = 2
                        },
                        new
                        {
                            SharedItemId = 3,
                            ItemId = 17,
                            ItemName = "preza.pdf",
                            UserId = 3
                        },
                        new
                        {
                            SharedItemId = 4,
                            ItemId = 18,
                            ItemName = "osobni-dokument.docx",
                            UserId = 1
                        },
                        new
                        {
                            SharedItemId = 5,
                            ItemId = 19,
                            ItemName = "Review.txt",
                            UserId = 2
                        },
                        new
                        {
                            SharedItemId = 6,
                            ItemId = 20,
                            ItemName = "Recepti.docx",
                            UserId = 3
                        },
                        new
                        {
                            SharedItemId = 7,
                            ItemId = 21,
                            ItemName = "notes.txt",
                            UserId = 1
                        },
                        new
                        {
                            SharedItemId = 8,
                            ItemId = 22,
                            ItemName = "summary.pdf",
                            UserId = 2
                        },
                        new
                        {
                            SharedItemId = 9,
                            ItemId = 23,
                            ItemName = "picture.jpg",
                            UserId = 3
                        },
                        new
                        {
                            SharedItemId = 10,
                            ItemId = 24,
                            ItemName = "tasklist.docx",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiskId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 607, DateTimeKind.Utc).AddTicks(3483),
                            DiskId = 1,
                            Email = "luka@gmail.com",
                            Password = "12345"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 607, DateTimeKind.Utc).AddTicks(4204),
                            DiskId = 2,
                            Email = "ante@gmail.com",
                            Password = "12345"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 607, DateTimeKind.Utc).AddTicks(4207),
                            DiskId = 3,
                            Email = "mate@gmail.com",
                            Password = "12345"
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Files", b =>
                {
                    b.HasBaseType("Drive.Data.Entities.Models.Item");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("File");

                    b.HasData(
                        new
                        {
                            ItemId = 15,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1435),
                            DiskId = 1,
                            Name = "domaci.docx",
                            ParentFolderId = 1,
                            Content = "Content for Dump Domaci Notes"
                        },
                        new
                        {
                            ItemId = 16,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1620),
                            DiskId = 1,
                            Name = "predavanje.txt",
                            ParentFolderId = 2,
                            Content = "Content for Fesb Predavanja Slides"
                        },
                        new
                        {
                            ItemId = 17,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1623),
                            DiskId = 1,
                            Name = "preza.pdf",
                            ParentFolderId = 3,
                            Content = "Content for Web Programiranje Code"
                        },
                        new
                        {
                            ItemId = 18,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1624),
                            DiskId = 1,
                            Name = "osobni-dokument.docx",
                            ParentFolderId = 5,
                            Content = "Content for Personal Documents"
                        },
                        new
                        {
                            ItemId = 19,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1626),
                            DiskId = 1,
                            Name = "Review.txt",
                            Content = "Review"
                        },
                        new
                        {
                            ItemId = 20,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1628),
                            DiskId = 1,
                            Name = "Recepti.docx",
                            Content = "Content for Recepti"
                        },
                        new
                        {
                            ItemId = 21,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1629),
                            DiskId = 1,
                            Name = "notes.txt",
                            ParentFolderId = 2,
                            Content = "Class notes"
                        },
                        new
                        {
                            ItemId = 22,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1630),
                            DiskId = 1,
                            Name = "summary.pdf",
                            ParentFolderId = 6,
                            Content = "Project summary"
                        },
                        new
                        {
                            ItemId = 23,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1631),
                            DiskId = 1,
                            Name = "picture-description.txt",
                            ParentFolderId = 4,
                            Content = "A random picture"
                        },
                        new
                        {
                            ItemId = 24,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1633),
                            DiskId = 1,
                            Name = "tasklist.docx",
                            ParentFolderId = 9,
                            Content = "List of tasks"
                        },
                        new
                        {
                            ItemId = 25,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1649),
                            DiskId = 2,
                            Name = "thesis.docx",
                            ParentFolderId = 10,
                            Content = "Thesis draft"
                        },
                        new
                        {
                            ItemId = 26,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1650),
                            DiskId = 3,
                            Name = "system-notes.txt",
                            ParentFolderId = 11,
                            Content = "Notes on OS"
                        },
                        new
                        {
                            ItemId = 27,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1651),
                            DiskId = 3,
                            Name = "linux-guide.pdf",
                            ParentFolderId = 12,
                            Content = "Linux guide"
                        },
                        new
                        {
                            ItemId = 28,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1680),
                            DiskId = 3,
                            Name = "windows-faq.docx",
                            ParentFolderId = 13,
                            Content = "Windows FAQ"
                        },
                        new
                        {
                            ItemId = 29,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(1680),
                            DiskId = 3,
                            Name = "study-plan.txt",
                            ParentFolderId = 14,
                            Content = "Plan for studying"
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Folder", b =>
                {
                    b.HasBaseType("Drive.Data.Entities.Models.Item");

                    b.HasDiscriminator().HasValue("Folder");

                    b.HasData(
                        new
                        {
                            ItemId = 2,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(96),
                            DiskId = 1,
                            Name = "Fesb-predavanja"
                        },
                        new
                        {
                            ItemId = 3,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(525),
                            DiskId = 1,
                            Name = "Web-prog",
                            ParentFolderId = 2
                        },
                        new
                        {
                            ItemId = 4,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(680),
                            DiskId = 1,
                            Name = "Slike"
                        },
                        new
                        {
                            ItemId = 1,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(682),
                            DiskId = 1,
                            Name = "Moje slike",
                            ParentFolderId = 4
                        },
                        new
                        {
                            ItemId = 5,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(683),
                            DiskId = 1,
                            Name = "Dokumenti"
                        },
                        new
                        {
                            ItemId = 6,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(688),
                            DiskId = 1,
                            Name = "Projektni-zadaci",
                            ParentFolderId = 2
                        },
                        new
                        {
                            ItemId = 7,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(690),
                            DiskId = 2,
                            Name = "Recepti"
                        },
                        new
                        {
                            ItemId = 8,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(691),
                            DiskId = 2,
                            Name = "Svasta"
                        },
                        new
                        {
                            ItemId = 9,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(692),
                            DiskId = 2,
                            Name = "Projekti"
                        },
                        new
                        {
                            ItemId = 10,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(693),
                            DiskId = 2,
                            Name = "Zavrsni-rad",
                            ParentFolderId = 9
                        },
                        new
                        {
                            ItemId = 11,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(694),
                            DiskId = 3,
                            Name = "Operacijski-sustavi"
                        },
                        new
                        {
                            ItemId = 12,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(695),
                            DiskId = 3,
                            Name = "Linux",
                            ParentFolderId = 11
                        },
                        new
                        {
                            ItemId = 13,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(696),
                            DiskId = 3,
                            Name = "Windows",
                            ParentFolderId = 11
                        },
                        new
                        {
                            ItemId = 14,
                            CreatedAt = new DateTime(2024, 12, 28, 14, 49, 26, 608, DateTimeKind.Utc).AddTicks(697),
                            DiskId = 3,
                            Name = "Folder-za-faks"
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Comment", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.Item", "Item")
                        .WithMany("Comments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Disk", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.User", "User")
                        .WithOne("Disk")
                        .HasForeignKey("Drive.Data.Entities.Models.Disk", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Item", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.Disk", "Disk")
                        .WithMany("Items")
                        .HasForeignKey("DiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.Folder", null)
                        .WithMany("Items")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Drive.Data.Entities.Models.Folder", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderItemId");

                    b.Navigation("Disk");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.SharedItem", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.User", "User")
                        .WithMany("SharedItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Disk", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Item", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Disk")
                        .IsRequired();

                    b.Navigation("SharedItems");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Folder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
